apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-env
  name: auto-env
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auto-env
  type: ClusterIP